### ISSUE TITLE
turnd

### ISSUE THREAD

**Issue by backkem** [gortc/turn#1]
Should we create a basic turn server implementation, E.g.: gortc/turnd?

**Comment by ernado** [comment]
Yes, of course.

**Comment by ernado** [comment]
But we need something like `stun.Client` and `stun.Agent` for turn. Also seems like we need to do something with multiplexing.

**Comment by ernado** [comment]
Maybe we shoud just create something like gortc/gortcd

**Comment by backkem** [comment]
One reason to keep separate daemons is because they will likely have different resource requirements. E.g.: a TURN server has higher bandwidth requirements than the others.

**Comment by ernado** [comment]
The TURN functionity can be disabled (how it is done in coturn) by configuration.

**Comment by backkem** [comment]
You're right. That would probably also avoid quite some duplicate effort.

**Comment by backkem** [comment]
I guess we can deprecate gortc/stund and close this issue?

**Comment by ernado** [comment]
The [gortcd](https://github.com/gortc/gortcd) implements TURN server.
I'm leaving [stund](https://github.com/gortc/stund) as simple STUN server implementation for example purpose.
