### ISSUE TITLE
XorRelayedAddress named RelayedAddress

### ISSUE THREAD

**Issue by Sean-Der** [gortc/turn#18]
I was confused at first by the name, would it be worth doing a type alias (or breaking the API) to fix? 

https://godoc.org/github.com/gortc/turn#RelayedAddress

**Comment by ernado** [comment]
I've added the `XOR` aliases for `PeerAddress` and `RelayedAddress`.
Probably we can safely replace  in next minor version.
Seems like I've tried to avoid the `RR` part in `XORRelayedAddress` and make names more simple, but it let to confusion, sorry.

Also I've fixed the documentation for RelayedAddress

**Comment by Sean-Der** [comment]
Awesome, thank you @ernado!

No need to apologize :) this library saved me so much time, one tiny confusion was all. I was able to completely port `pion/turn` in one weekend so the library is really easy to use!
